// Placeholders for the search navigation bar input field

export const placeholders = [
  "Search for mouthwatering appetizers",
  "Search for epicurean delights",
  "Search for flavor-packed adventures",
  "Search for culinary treasures",
  "Search for palate-pleasing wonders",
  "Search for gastronomic marvels",
  "Search for delectable discoveries",
  "Search for savory sensations",
  "Search for mouthwatering masterpieces",
  "Search for culinary conquests",
  "Search for taste bud tantalizers",
  "Search for gourmet delights",
  "Search for flavor-filled fantasies",
  "Search for kitchen triumphs",
  "Search for delicious discoveries",
  "Search for savory delights",
  "Search for tasty temptations",
  "Search for culinary inspirations",
  "Search for palate-pleasing pleasures",
  "Search for homemade happiness",
  "Search for mouthwatering moments",
  "Search for savory surprises",
  "Search for culinary gems",
  "Search for indulgent pasta dishes",
  "Search for exotic international cuisines",
  "Search for breakfast delights",
  "Search for comforting casseroles",
  "Search for crowd-pleasing party snacks",
  "Search for elegant dinner party menus",
  "Search for taste bud thrills",
  "Search for gourmet treasures",
  "Search for mouthwatering marvels",
  "Search for epicurean adventures",
  "Search for palate-pleasing quests",
  "Search for gastronomic wonders",
  "Search for tantalizing treats",
  "Search for delicious delicacies",
  "Search for flavor-filled delights",
  "Search for culinary discoveries",
  "Search for taste bud adventures",
  "Search for mouthwatering journeys",
  "Search for gourmet experiences",
  "Search for delectable delights",
  "Search for culinary gems",
  "Search for taste bud delights",
  "Search for palate-pleasing experiences",
  "Search for flavor-filled explorations",
  "Search for epicurean indulgences",
  "Search for culinary revelations",
  "Search for delicious diversions",
  "Search for tantalizing tastes",
  "Search for gourmet pleasures",
  "Search for mouthwatering wonders",
];
